global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-products-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["172.17.0.1:9000"]
        labels:
          application: "api-products"